[server]
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#4f46e5"
backgroundColor = "#f4f4f5"
secondaryBackgroundColor = "#ffffff"
textColor = "#18181b"
font = "sans serif"
